requirement 09 completed
tryber/sd-013-b-project-trivia-react-redux pull request #555
Opened 2021-09-09 23:14 UTC by guiidc

Link Card Trello:
https://trello.com/c/z5uALd91/9-prioridade-3-tela-de-jogo-trivia-9-crie-o-placar-com-as-seguintes-caracter%C3%ADsticas

2021-09-09 23:41 UTC, luciobj requested changes
Reveja esses pontos por favor! :eyes:

2021-09-09 23:41 UTC, luciobj commented on src/pages/PageGame.jsx
> +            <Score score={ score } />
Você acha necessária essa componentização? :confused:

2021-09-09 23:41 UTC, luciobj commented on src/pages/PageGame.jsx
> +        gravatar: imgPath,
Acredito que o formato solicidatado não é exatamente esse. Você pode dar uma olhada e confirmar por favor? :point_up:

2021-09-10 00:02 UTC, guiidc commented on src/pages/PageGame.jsx
> +            <Score score={ score } />
Boa, acabei fazendo por achar que ia ser efetivo, mas acabou que fica melhor sem componetizar

2021-09-10 00:03 UTC, guiidc commented on src/pages/PageGame.jsx
> +        gravatar: imgPath,
realmente, está diferente

2021-09-10 11:05 UTC, leomartins1 approved these changes
Tudo certo ao meu ver. Bom trabalho!

2021-09-10 13:50 UTC, luciobj requested changes

2021-09-10 13:50 UTC, luciobj commented on src/pages/PageGame.jsx
> +    const teste = JSON.stringify(data);
O que você acha de mudar  nome dessa variavel para algo no padrão inglês, e mais intuitivo? 👍

2021-09-10 17:07 UTC, guiidc commented on src/pages/PageGame.jsx
> +    const teste = JSON.stringify(data);
retirei a variavel e coloquei o stringfy direto no setItem

2021-09-10 17:23 UTC, luciobj approved these changes
Ótimo, bem completo!

2021-09-10 17:59 UTC, merged